export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace" | "agent_event";

export type AgentEventType =
  | "thought"
  | "orchestrator_plan"
  | "subagent_spawned"
  | "subagent_status"
  | "subagent_done"
  | "blackboard_entry"
  | "agent_status"
  | "tool_call"
  | "high_risk_confirm";

/** Recognised blackboard entry kinds. ``BlackboardEntry.kind`` is filled by
 * the backend ``Blackboard.write()`` regex on the leading ``[tag]`` prefix.
 * ``null`` covers free-form entries — the front-end falls back to a regex on
 * ``text`` to keep the panel useful even when the agent forgets the prefix.
 * Source of truth: ``secbot/agent/blackboard.py`` ``KNOWN_KINDS``. */
export type BlackboardKind = "milestone" | "blocker" | "finding" | "progress";

/** Runtime status enum for an expert agent. Mirrors the backend
 * ``dashboard-aggregation.md §2.6`` enum. ``offline`` means "no manager
 * wired" or "binary missing"; ``idle`` means the manager is up but the agent
 * has no running task. */
export type AgentRuntimeStatus = "idle" | "running" | "queued" | "offline";

export interface OrchestratorPlanStep {
  title: string;
  detail?: string;
}

/** Status lifecycle for a tool_call agent_event.
 *
 * - running: non-critical tool executing
 * - critical: critical-risk tool awaiting user approval
 * - ok: tool completed successfully
 * - error: tool failed or was denied */
export type ToolCallStatus = "running" | "critical" | "ok" | "error";

export interface AgentEventPayload {
  type: AgentEventType;
  agent?: string;
  content?: string;
  steps?: OrchestratorPlanStep[];
  task_id?: string;
  label?: string;
  task_description?: string;
  phase?: string;
  iteration?: number;
  tool_events?: unknown[];
  status?: "ok" | "error";
  result?: string;
  id?: string;
  agent_name?: string;
  text?: string;
  timestamp?: number;

  // ── tool_call event fields (B5 payload) ──────────────────────────
  /** Unique tool-call ID from the provider (pairs running→terminal). */
  tool_call_id?: string;
  /** Name of the tool/skill being executed. */
  tool_name?: string;
  /** Arguments passed to the tool (display-only). */
  tool_args?: Record<string, unknown>;
  /** Execution duration in ms (present only on terminal frames). */
  duration_ms?: number;
  /** Reason string when status="error" (e.g. "user_denied", "timeout"). */
  reason?: string;
  /** Granular tool_call status (discriminated from generic status). */
  tool_status?: ToolCallStatus;

  // ── blackboard_entry event fields ─────────────────────────────────
  /** Kind extracted from the leading ``[tag]`` prefix on ``text``. ``null``
   * means the agent did not prefix the entry; the panel may apply its own
   * fallback regex. */
  kind?: BlackboardKind | null;

  // ── agent_status event fields (B6 payload) ────────────────────────
  /** Authoritative runtime status of the expert agent identified by
   * ``agent_name``. Sidebar agent chips key off this enum. */
  agent_status?: AgentRuntimeStatus;
  /** ID of the task that owns this status snapshot. ``null`` when the
   * agent has no in-flight task. */
  current_task_id?: string | null;
  /** ISO-8601 UTC timestamp of the last lifecycle / heartbeat update. */
  last_heartbeat_at?: string | null;

  // ── high_risk_confirm event fields ────────────────────────────────
  /** Server-minted correlation ID for approve/deny round-trip. */
  ask_id?: string;
  /** Skill display name shown to the user. */
  skill?: string;
  /** Human-readable summary for the confirmation card. */
  summary_for_user?: string;
  /** Timeout in seconds before auto-deny. */
  timeout_sec?: number;
}

/** Legacy alias for blackboard entry shape (used by BlackboardCard). */
export type BlackboardEntry = Pick<
  AgentEventPayload,
  "id" | "agent_name" | "text" | "timestamp" | "kind"
>;

/** Expert-agent registry row enriched with optional runtime fields, returned
 * by ``GET /api/agents`` (with or without ``?include_status=true``). The
 * runtime fields are only present when the query flag is set; consumers
 * MUST treat them as optional. Source: ``dashboard-aggregation.md §2.6``. */
export interface AgentRegistryRow {
  name: string;
  display_name?: string;
  description?: string;
  scoped_skills?: string[];
  max_iterations?: number;
  source_path?: string | null;
  available?: boolean;
  required_binaries?: string[];
  missing_binaries?: string[];
  // Runtime fields (only when ?include_status=true).
  status?: AgentRuntimeStatus;
  current_task_id?: string | null;
  progress?: number | null;
  last_heartbeat_at?: string | null;
}

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Optional answer choices for a pending ask_user question. */
  buttons?: string[][];
  /** Source tool for a blocking prompt, e.g. ask_user or request_approval. */
  toolName?: "ask_user" | "request_approval" | string;
  promptKind?: "question" | "approval";
  /** Correlation ID for a high-risk confirmation dialog. When set, the
   * answer routes via ``scan.user_reply`` instead of a regular message. */
  askId?: string;
  /** Pre-formatted detail text for approval prompts. */
  approvalDetail?: string;
  /** Agent event payload when kind is ``agent_event``. */
  agentEvent?: AgentEventPayload;
  /** Normalised agent name (snake_case registry key) that produced this
   * message. Inferred from the most recent ``agent_event`` frame so plain
   * ``delta`` / ``message`` turns can still carry the correct avatar colour
   * and meta label. */
  agentName?: string;
  /** Tool-call events that belong to this assistant turn.  The stream hook
   * merges consecutive ``agent_event`` ``tool_call`` frames into the
   * preceding assistant message from the same agent so the UI can render
   * them inside the bubble rather than as detached cards. */
  toolCalls?: AgentEventPayload[];
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
  }>;
  /**
   * Active provider slot — mirrors the one AgentLoop resolves for the
   * current ``agent.model`` / ``agent.provider``. ``api_base`` is plain text
   * (non-sensitive); ``api_key_masked`` is shaped like ``sk-****abcd`` so
   * the UI can confirm a key is saved without exposing it.
   */
  custom: {
    api_base: string;
    api_key_masked: string;
    has_api_key: boolean;
  };
  /**
   * Per-provider config snapshot keyed by provider name (e.g. ``openai``,
   * ``deepseek``, ``openrouter``). Lets the Provider dropdown swap Base URL
   * and API Key hints instantly without a network round-trip.
   * ``default_api_base`` is the spec-level fallback URL (e.g.
   * ``https://api.deepseek.com``) shown as a placeholder when the user has
   * not overridden ``api_base`` in config.
   */
  provider_configs: Record<string, {
    api_base: string;
    default_api_base: string;
    api_key_masked: string;
    has_api_key: boolean;
  }>;
  runtime: {
    config_path: string;
  };
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
  /** OpenAI-compatible endpoint URL, e.g. ``https://api.openai.com/v1``. */
  api_base?: string;
  /**
   * OpenAI-compatible API key. Sent over the ``X-Settings-Api-Key`` request
   * header (never in the URL). Omit the field to keep the existing key;
   * empty string clears it.
   */
  api_key?: string;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | {
      event: "attached";
      chat_id: string;
      /** Authoritative backend flag: ``true`` when the agent is currently
       * processing a turn for ``chat_id`` (user message submitted but no
       * matching ``turn_end`` yet). The webui uses this to decide whether
       * to show the Stop button after a refresh or chat switch — it must
       * never be inferred from persisted ``tool_calls`` rows, which can
       * linger past the actual turn boundary. Absent on older servers. */
      active_turn?: boolean;
    }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      buttons?: string[][];
      /** Original prompt before the websocket text fallback appends buttons. */
      button_prompt?: string;
      /** Source tool for structured prompts. */
      tool_name?: "ask_user" | "request_approval" | string;
      prompt_kind?: "question" | "approval";
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress";
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | { event: "turn_end"; chat_id: string }
  | { event: "session_updated"; chat_id: string }
  | {
      event: "agent_event";
      chat_id: string;
      type: AgentEventType;
      payload: AgentEventPayload;
      timestamp: string;
    }
  | { event: "error"; chat_id?: string; detail?: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | { type: "stop"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    }
  | {
      /** Reply to a ``high_risk_confirm`` dialog. Spec:
       * ``websocket-protocol.md`` §4 (``scan.user_reply``). */
      type: "scan.user_reply";
      ask_id: string;
      decision: "approve" | "deny";
      reason?: string;
    };

// ────────────────────────────────────────────────────────────────────────
// Notification center (P2) — schema matches the backend contract shipped
// in ``05-10-p2-notification-activity`` (archived PRD). Shape is frozen
// by the REST responses, NOT by this file — if the backend changes the
// contract, update both sides.
// ────────────────────────────────────────────────────────────────────────

/** Notification type emitted by backend. Unknown values must still
 * render (F5: degrade-don't-crash) — consumers treat anything outside
 * the union as a generic "info" notification. */
export type NotificationKind =
  | "critical_vuln"
  | "scan_failed"
  | "scan_completed"
  | "high_risk_confirm";

export interface Notification {
  id: string;
  /** See :type:`NotificationKind`. Typed as string to allow forward
   * compat with kinds the backend may add later. */
  kind: string;
  title: string;
  body: string;
  /** ISO-8601 UTC timestamp. */
  created_at: string;
  read: boolean;
  /** Optional in-app deep link (e.g. ``/tasks/TASK-...``). When set,
   * clicking the notification navigates there. */
  link?: string | null;
}

export interface NotificationListResponse {
  items: Notification[];
  total: number;
  limit: number;
  offset: number;
  unread_count: number;
}

// ────────────────────────────────────────────────────────────────────────
// Activity event stream (P2). Two wire shapes feed the same UI list:
//
// 1. REST ``GET /api/events`` — canonical records with ``id``, ``level``,
//    ``source``, ``task_id``, ``message``.
// 2. WS ``activity_event`` — live broadcast without a stable ``id``
//    field; carries ``chat_id``, ``category``, ``agent``, ``step``,
//    ``duration_ms``. The hook normalises both into :type:`ActivityEvent`.
// ────────────────────────────────────────────────────────────────────────

export type ActivityLevel = "critical" | "warning" | "info" | "ok";

export type ActivitySource =
  | "weak_password"
  | "port_scan"
  | "asset_discovery"
  | "report"
  | "orchestrator";

export type ActivityCategory = "thought" | "tool_call" | "tool_result";

/** Canonical UI shape for one activity-stream row.
 *
 * ``id`` is stable across REST reloads; for WS-originated rows the hook
 * derives it from ``chat_id|timestamp|step`` so dedupe works when the
 * same event later surfaces via REST. */
export interface ActivityEvent {
  id: string;
  timestamp: string;
  level: ActivityLevel;
  source: ActivitySource;
  message: string;
  task_id?: string | null;
  /** WS-only enrichment. */
  chat_id?: string | null;
  agent?: string | null;
  step?: string | null;
  category?: ActivityCategory | null;
  duration_ms?: number | null;
}

export interface ActivityEventListResponse {
  items: ActivityEvent[];
}

/** Raw WS payload broadcast by :func:`WebSocketChannel.broadcast_activity_event`.
 * Kept separate from :type:`ActivityEvent` because the WS frame omits
 * ``id`` / ``level`` / ``source`` — the hook derives those client-side. */
export interface ActivityEventFrame {
  event: "activity_event";
  chat_id: string;
  category: ActivityCategory | string;
  agent?: string;
  step?: string;
  timestamp: string;
  duration_ms?: number;
}
